// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jikken.proto

#ifndef PROTOBUF_jikken_2eproto__INCLUDED
#define PROTOBUF_jikken_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_jikken_2eproto();
void protobuf_AssignDesc_jikken_2eproto();
void protobuf_ShutdownFile_jikken_2eproto();

class AAA;

// ===================================================================

class AAA : public ::google::protobuf::Message {
 public:
  AAA();
  virtual ~AAA();

  AAA(const AAA& from);

  inline AAA& operator=(const AAA& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AAA& default_instance();

  void Swap(AAA* other);

  // implements Message ----------------------------------------------

  AAA* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AAA& from);
  void MergeFrom(const AAA& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string str = 1;
  inline bool has_str() const;
  inline void clear_str();
  static const int kStrFieldNumber = 1;
  inline const ::std::string& str() const;
  inline void set_str(const ::std::string& value);
  inline void set_str(const char* value);
  inline void set_str(const char* value, size_t size);
  inline ::std::string* mutable_str();
  inline ::std::string* release_str();
  inline void set_allocated_str(::std::string* str);

  // required int32 x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:AAA)
 private:
  inline void set_has_str();
  inline void clear_has_str();
  inline void set_has_x();
  inline void clear_has_x();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* str_;
  ::google::protobuf::int32 x_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_jikken_2eproto();
  friend void protobuf_AssignDesc_jikken_2eproto();
  friend void protobuf_ShutdownFile_jikken_2eproto();

  void InitAsDefaultInstance();
  static AAA* default_instance_;
};
// ===================================================================


// ===================================================================

// AAA

// required string str = 1;
inline bool AAA::has_str() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AAA::set_has_str() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AAA::clear_has_str() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AAA::clear_str() {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    str_->clear();
  }
  clear_has_str();
}
inline const ::std::string& AAA::str() const {
  return *str_;
}
inline void AAA::set_str(const ::std::string& value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void AAA::set_str(const char* value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void AAA::set_str(const char* value, size_t size) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AAA::mutable_str() {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  return str_;
}
inline ::std::string* AAA::release_str() {
  clear_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = str_;
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AAA::set_allocated_str(::std::string* str) {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    delete str_;
  }
  if (str) {
    set_has_str();
    str_ = str;
  } else {
    clear_has_str();
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 x = 2;
inline bool AAA::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AAA::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AAA::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AAA::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 AAA::x() const {
  return x_;
}
inline void AAA::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_jikken_2eproto__INCLUDED
