// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_MATCHINGINFO_DEMOBATTLE_H_
#define FLATBUFFERS_GENERATED_MATCHINGINFO_DEMOBATTLE_H_

#include "flatbuffers/flatbuffers.h"


namespace DemoBattle {

struct TargetCharacterInfo;
struct MatchingInfo;

struct TargetCharacterInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int32_t character_id() const { return GetField<int32_t>(4, 0); }
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(6); }
  int16_t base_hp() const { return GetField<int16_t>(8, 100); }
  int16_t base_mana() const { return GetField<int16_t>(10, 100); }
  int16_t physical_attack() const { return GetField<int16_t>(12, 10); }
  int16_t magical_attack() const { return GetField<int16_t>(14, 10); }
  int16_t physical_defense() const { return GetField<int16_t>(16, 10); }
  int16_t magical_defense() const { return GetField<int16_t>(18, 10); }
  int16_t speed() const { return GetField<int16_t>(20, 10); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, 4 /* character_id */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* name */) &&
           verifier.Verify(name()) &&
           VerifyField<int16_t>(verifier, 8 /* base_hp */) &&
           VerifyField<int16_t>(verifier, 10 /* base_mana */) &&
           VerifyField<int16_t>(verifier, 12 /* physical_attack */) &&
           VerifyField<int16_t>(verifier, 14 /* magical_attack */) &&
           VerifyField<int16_t>(verifier, 16 /* physical_defense */) &&
           VerifyField<int16_t>(verifier, 18 /* magical_defense */) &&
           VerifyField<int16_t>(verifier, 20 /* speed */) &&
           verifier.EndTable();
  }
};

struct TargetCharacterInfoBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_character_id(int32_t character_id) { fbb_.AddElement<int32_t>(4, character_id, 0); }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(6, name); }
  void add_base_hp(int16_t base_hp) { fbb_.AddElement<int16_t>(8, base_hp, 100); }
  void add_base_mana(int16_t base_mana) { fbb_.AddElement<int16_t>(10, base_mana, 100); }
  void add_physical_attack(int16_t physical_attack) { fbb_.AddElement<int16_t>(12, physical_attack, 10); }
  void add_magical_attack(int16_t magical_attack) { fbb_.AddElement<int16_t>(14, magical_attack, 10); }
  void add_physical_defense(int16_t physical_defense) { fbb_.AddElement<int16_t>(16, physical_defense, 10); }
  void add_magical_defense(int16_t magical_defense) { fbb_.AddElement<int16_t>(18, magical_defense, 10); }
  void add_speed(int16_t speed) { fbb_.AddElement<int16_t>(20, speed, 10); }
  TargetCharacterInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  TargetCharacterInfoBuilder &operator=(const TargetCharacterInfoBuilder &);
  flatbuffers::Offset<TargetCharacterInfo> Finish() {
    auto o = flatbuffers::Offset<TargetCharacterInfo>(fbb_.EndTable(start_, 9));
    return o;
  }
};

inline flatbuffers::Offset<TargetCharacterInfo> CreateTargetCharacterInfo(flatbuffers::FlatBufferBuilder &_fbb,
   int32_t character_id = 0,
   flatbuffers::Offset<flatbuffers::String> name = 0,
   int16_t base_hp = 100,
   int16_t base_mana = 100,
   int16_t physical_attack = 10,
   int16_t magical_attack = 10,
   int16_t physical_defense = 10,
   int16_t magical_defense = 10,
   int16_t speed = 10) {
  TargetCharacterInfoBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_character_id(character_id);
  builder_.add_speed(speed);
  builder_.add_magical_defense(magical_defense);
  builder_.add_physical_defense(physical_defense);
  builder_.add_magical_attack(magical_attack);
  builder_.add_physical_attack(physical_attack);
  builder_.add_base_mana(base_mana);
  builder_.add_base_hp(base_hp);
  return builder_.Finish();
}

struct MatchingInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const flatbuffers::String *host() const { return GetPointer<const flatbuffers::String *>(4); }
  const flatbuffers::String *ws_path() const { return GetPointer<const flatbuffers::String *>(6); }
  uint16_t ws_port() const { return GetField<uint16_t>(8, 0); }
  const flatbuffers::String *udp_host() const { return GetPointer<const flatbuffers::String *>(10); }
  const flatbuffers::Vector<uint16_t> *udp_ports() const { return GetPointer<const flatbuffers::Vector<uint16_t> *>(12); }
  int32_t player_id() const { return GetField<int32_t>(14, 0); }
  int32_t target_id() const { return GetField<int32_t>(16, 0); }
  const flatbuffers::String *target_name() const { return GetPointer<const flatbuffers::String *>(18); }
  const flatbuffers::Vector<flatbuffers::Offset<TargetCharacterInfo>> *target_characters() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<TargetCharacterInfo>> *>(20); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* host */) &&
           verifier.Verify(host()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* ws_path */) &&
           verifier.Verify(ws_path()) &&
           VerifyField<uint16_t>(verifier, 8 /* ws_port */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 10 /* udp_host */) &&
           verifier.Verify(udp_host()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 12 /* udp_ports */) &&
           verifier.Verify(udp_ports()) &&
           VerifyField<int32_t>(verifier, 14 /* player_id */) &&
           VerifyField<int32_t>(verifier, 16 /* target_id */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 18 /* target_name */) &&
           verifier.Verify(target_name()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 20 /* target_characters */) &&
           verifier.Verify(target_characters()) &&
           verifier.VerifyVectorOfTables(target_characters()) &&
           verifier.EndTable();
  }
};

struct MatchingInfoBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_host(flatbuffers::Offset<flatbuffers::String> host) { fbb_.AddOffset(4, host); }
  void add_ws_path(flatbuffers::Offset<flatbuffers::String> ws_path) { fbb_.AddOffset(6, ws_path); }
  void add_ws_port(uint16_t ws_port) { fbb_.AddElement<uint16_t>(8, ws_port, 0); }
  void add_udp_host(flatbuffers::Offset<flatbuffers::String> udp_host) { fbb_.AddOffset(10, udp_host); }
  void add_udp_ports(flatbuffers::Offset<flatbuffers::Vector<uint16_t>> udp_ports) { fbb_.AddOffset(12, udp_ports); }
  void add_player_id(int32_t player_id) { fbb_.AddElement<int32_t>(14, player_id, 0); }
  void add_target_id(int32_t target_id) { fbb_.AddElement<int32_t>(16, target_id, 0); }
  void add_target_name(flatbuffers::Offset<flatbuffers::String> target_name) { fbb_.AddOffset(18, target_name); }
  void add_target_characters(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TargetCharacterInfo>>> target_characters) { fbb_.AddOffset(20, target_characters); }
  MatchingInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  MatchingInfoBuilder &operator=(const MatchingInfoBuilder &);
  flatbuffers::Offset<MatchingInfo> Finish() {
    auto o = flatbuffers::Offset<MatchingInfo>(fbb_.EndTable(start_, 9));
    return o;
  }
};

inline flatbuffers::Offset<MatchingInfo> CreateMatchingInfo(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<flatbuffers::String> host = 0,
   flatbuffers::Offset<flatbuffers::String> ws_path = 0,
   uint16_t ws_port = 0,
   flatbuffers::Offset<flatbuffers::String> udp_host = 0,
   flatbuffers::Offset<flatbuffers::Vector<uint16_t>> udp_ports = 0,
   int32_t player_id = 0,
   int32_t target_id = 0,
   flatbuffers::Offset<flatbuffers::String> target_name = 0,
   flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TargetCharacterInfo>>> target_characters = 0) {
  MatchingInfoBuilder builder_(_fbb);
  builder_.add_target_characters(target_characters);
  builder_.add_target_name(target_name);
  builder_.add_target_id(target_id);
  builder_.add_player_id(player_id);
  builder_.add_udp_ports(udp_ports);
  builder_.add_udp_host(udp_host);
  builder_.add_ws_path(ws_path);
  builder_.add_host(host);
  builder_.add_ws_port(ws_port);
  return builder_.Finish();
}

inline const DemoBattle::MatchingInfo *GetMatchingInfo(const void *buf) { return flatbuffers::GetRoot<DemoBattle::MatchingInfo>(buf); }

inline bool VerifyMatchingInfoBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<DemoBattle::MatchingInfo>(); }

inline void FinishMatchingInfoBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<DemoBattle::MatchingInfo> root) { fbb.Finish(root); }

}  // namespace DemoBattle

#endif  // FLATBUFFERS_GENERATED_MATCHINGINFO_DEMOBATTLE_H_
