// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_NOTIFYENDPHASE_DEMOBATTLE_H_
#define FLATBUFFERS_GENERATED_NOTIFYENDPHASE_DEMOBATTLE_H_

#include "flatbuffers/flatbuffers.h"


namespace DemoBattle {

struct NotifyEndPhase;

struct NotifyEndPhase FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int32_t seq_id() const { return GetField<int32_t>(4, 0); }
  int32_t reason_code() const { return GetField<int32_t>(6, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, 4 /* seq_id */) &&
           VerifyField<int32_t>(verifier, 6 /* reason_code */) &&
           verifier.EndTable();
  }
};

struct NotifyEndPhaseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_seq_id(int32_t seq_id) { fbb_.AddElement<int32_t>(4, seq_id, 0); }
  void add_reason_code(int32_t reason_code) { fbb_.AddElement<int32_t>(6, reason_code, 0); }
  NotifyEndPhaseBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  NotifyEndPhaseBuilder &operator=(const NotifyEndPhaseBuilder &);
  flatbuffers::Offset<NotifyEndPhase> Finish() {
    auto o = flatbuffers::Offset<NotifyEndPhase>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<NotifyEndPhase> CreateNotifyEndPhase(flatbuffers::FlatBufferBuilder &_fbb,
   int32_t seq_id = 0,
   int32_t reason_code = 0) {
  NotifyEndPhaseBuilder builder_(_fbb);
  builder_.add_reason_code(reason_code);
  builder_.add_seq_id(seq_id);
  return builder_.Finish();
}

inline const NotifyEndPhase *GetNotifyEndPhase(const void *buf) { return flatbuffers::GetRoot<NotifyEndPhase>(buf); }

inline bool VerifyNotifyEndPhaseBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<NotifyEndPhase>(); }

inline void FinishNotifyEndPhaseBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<NotifyEndPhase> root) { fbb.Finish(root); }

}  // namespace DemoBattle

#endif  // FLATBUFFERS_GENERATED_NOTIFYENDPHASE_DEMOBATTLE_H_
