// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_NOTIFYBUFFACTION_DEMOBATTLE_H_
#define FLATBUFFERS_GENERATED_NOTIFYBUFFACTION_DEMOBATTLE_H_

#include "flatbuffers/flatbuffers.h"


namespace DemoBattle {

struct BuffDetail;
struct NotifyBuffAction;

MANUALLY_ALIGNED_STRUCT(4) BuffDetail FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t character_id_;
  int32_t target_id_;
  int32_t action_id_;
  int32_t buff_id_;

 public:
  BuffDetail(int32_t character_id, int32_t target_id, int32_t action_id, int32_t buff_id)
    : character_id_(flatbuffers::EndianScalar(character_id)), target_id_(flatbuffers::EndianScalar(target_id)), action_id_(flatbuffers::EndianScalar(action_id)), buff_id_(flatbuffers::EndianScalar(buff_id)) { }

  int32_t character_id() const { return flatbuffers::EndianScalar(character_id_); }
  int32_t target_id() const { return flatbuffers::EndianScalar(target_id_); }
  int32_t action_id() const { return flatbuffers::EndianScalar(action_id_); }
  int32_t buff_id() const { return flatbuffers::EndianScalar(buff_id_); }
};
STRUCT_END(BuffDetail, 16);

struct NotifyBuffAction FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  int32_t seq_id() const { return GetField<int32_t>(4, 0); }
  const flatbuffers::Vector<const BuffDetail *> *actions() const { return GetPointer<const flatbuffers::Vector<const BuffDetail *> *>(6); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, 4 /* seq_id */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* actions */) &&
           verifier.Verify(actions()) &&
           verifier.EndTable();
  }
};

struct NotifyBuffActionBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_seq_id(int32_t seq_id) { fbb_.AddElement<int32_t>(4, seq_id, 0); }
  void add_actions(flatbuffers::Offset<flatbuffers::Vector<const BuffDetail *>> actions) { fbb_.AddOffset(6, actions); }
  NotifyBuffActionBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  NotifyBuffActionBuilder &operator=(const NotifyBuffActionBuilder &);
  flatbuffers::Offset<NotifyBuffAction> Finish() {
    auto o = flatbuffers::Offset<NotifyBuffAction>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<NotifyBuffAction> CreateNotifyBuffAction(flatbuffers::FlatBufferBuilder &_fbb,
   int32_t seq_id = 0,
   flatbuffers::Offset<flatbuffers::Vector<const BuffDetail *>> actions = 0) {
  NotifyBuffActionBuilder builder_(_fbb);
  builder_.add_actions(actions);
  builder_.add_seq_id(seq_id);
  return builder_.Finish();
}

inline const NotifyBuffAction *GetNotifyBuffAction(const void *buf) { return flatbuffers::GetRoot<NotifyBuffAction>(buf); }

inline bool VerifyNotifyBuffActionBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<NotifyBuffAction>(); }

inline void FinishNotifyBuffActionBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<NotifyBuffAction> root) { fbb.Finish(root); }

}  // namespace DemoBattle

#endif  // FLATBUFFERS_GENERATED_NOTIFYBUFFACTION_DEMOBATTLE_H_
